/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface BouncyNumber {
        "next": number;
    }
    interface NumberCounter {
        "countName": string;
        "subtitle": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBouncyNumberElement extends Components.BouncyNumber, HTMLStencilElement {
    }
    var HTMLBouncyNumberElement: {
        prototype: HTMLBouncyNumberElement;
        new (): HTMLBouncyNumberElement;
    };
    interface HTMLNumberCounterElement extends Components.NumberCounter, HTMLStencilElement {
    }
    var HTMLNumberCounterElement: {
        prototype: HTMLNumberCounterElement;
        new (): HTMLNumberCounterElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "bouncy-number": HTMLBouncyNumberElement;
        "number-counter": HTMLNumberCounterElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface BouncyNumber {
        "next"?: number;
    }
    interface NumberCounter {
        "countName"?: string;
        "subtitle"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "bouncy-number": BouncyNumber;
        "number-counter": NumberCounter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "bouncy-number": LocalJSX.BouncyNumber & JSXBase.HTMLAttributes<HTMLBouncyNumberElement>;
            "number-counter": LocalJSX.NumberCounter & JSXBase.HTMLAttributes<HTMLNumberCounterElement>;
        }
    }
}
